# Generated by Django 5.1.5 on 2025-02-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='allergy_info',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='diet_info',
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
