# Generated by Django 5.1.5 on 2025-02-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dish_allergy_info_remove_dish_diet_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='amount',
            field=models.FloatField(blank=True, help_text='Amount in grams or ml', null=True),
        ),
    ]
